In [2]:
from ultralytics import YOLO
model = YOLO("../models/model2.pt")
model.to("cuda")

In [48]:
results = model('../testImageFolder/output_image.png', device="cpu", conf=0.6, project="results", name="acc",save=True)
for result in results:
    #탐지된 객체이름
    className = result.boxes.cls.tolist()
    #탐지된 객체 정확도
    acc = result.boxes.conf.tolist()
    #탐지된 객체 xy좌표
    xy_list = result.masks.xyn


image 1/1 c:\Team_Project-1\testpage\..\testImageFolder\output_image.png: 320x416 5 boxs, 151.3ms
Speed: 2.1ms preprocess, 151.3ms inference, 3.0ms postprocess per image at shape (1, 3, 320, 416)


In [49]:

print(xy_list[0])


[[     0.5024     0.17949]
 [    0.49038     0.19551]
 [    0.49038     0.19872]
 [    0.48558     0.20513]
 [    0.48317     0.20513]
 [    0.48077     0.20833]
 [    0.48077     0.21474]
 [    0.47837     0.21795]
 [    0.47837     0.22115]
 [    0.47115     0.23077]
 [    0.47115     0.23718]
 [    0.46635     0.24359]
 [    0.46394     0.24359]
 [    0.46154     0.24679]
 [    0.46154     0.25321]
 [    0.45433     0.26282]
 [    0.45433     0.26603]
 [    0.45192     0.26923]
 [    0.45192     0.27244]
 [    0.44231     0.28526]
 [    0.44231     0.28846]
 [    0.43269     0.30128]
 [    0.43269     0.30769]
 [    0.43029      0.3109]
 [    0.43029      0.3141]
 [    0.42308     0.32372]
 [    0.42308     0.32692]
 [    0.41827     0.33333]
 [    0.41587     0.33333]
 [    0.41346     0.33654]
 [    0.41346     0.33974]
 [    0.40385     0.35256]
 [    0.40385     0.36218]
 [    0.39423       0.375]
 [    0.39423     0.37821]
 [    0.38942     0.38462]
 [    0.38702     0.38462]
 

In [50]:
import open3d as o3d
import numpy as np

# read ply file
pcd = o3d.io.read_point_cloud('../testImageFolder/croptest1.ply')

# corners = [
#     [ 0.07, -0.02,  -0.50],
#     [ 0.07, 0.1,  -0.50],
#     [ 0.17, 0.15,  -0.50],
#     [ 0.26, 0.1,  -0.50],
#     [ 0.26, -0.02,  -0.50],
#     [ 0.17, -0.07,  -0.50]
# ]

new_xyz_list = np.c_[xy_list[0], np.full(xy_list[0].shape[0], -0.50)]
corners = np.array(new_xyz_list)

# Convert the corners array to have type float64
bounding_polygon = corners.astype("float64")

# Create a SelectionPolygonVolume
vol = o3d.visualization.SelectionPolygonVolume()

# You need to specify what axis to orient the polygon to.
# I choose the "Z" axis. I made the max value the maximum Z of
# the polygon vertices and the min value the minimum Z of the
# polygon vertices.
axis_num = 2
vol.orthogonal_axis = "Z"
# vol.axis_max = np.max(bounding_polygon[:, axis_num])
# vol.axis_min = np.min(bounding_polygon[:, axis_num])
vol.axis_max = 10.0
vol.axis_min = -10.0

# # Set all the Z values to 0 (they aren't needed since we specified what they
# # should be using just vol.axis_max and vol.axis_min).
bounding_polygon[:, axis_num] = 0

# Convert the np.array to a Vector3dVector
vol.bounding_polygon = o3d.utility.Vector3dVector(bounding_polygon)

print("vol = ", vol)
print("vol.orthogonal_axis = ", vol.orthogonal_axis)
print("vol.axis_min = ", vol.axis_min)
print("vol.axis_max = ", vol.axis_max)
print("vol.bounding_polygon = \n", np.asarray(vol.bounding_polygon))


# Crop the point cloud using the Vector3dVector
crop_pcd = vol.crop_point_cloud(pcd)

# 정육면체의 선 정보 (꼭지점을 연결하는 라인 인덱스)
lines = list()
for i in range(len(corners)):
    lines.append([i, (i+1) % len(corners)])

print(lines)

# 라인 정보 생성
lineset = o3d.geometry.LineSet()
lineset.points = o3d.utility.Vector3dVector(corners)
lineset.lines = o3d.utility.Vector2iVector(lines)


# visualize
o3d.visualization.draw_geometries([crop_pcd, lineset])
# o3d.visualization.draw_geometries([pcd, lineset])

vol =  SelectionPolygonVolume, access its members:
orthogonal_axis, bounding_polygon, axis_min, axis_max
vol.orthogonal_axis =  Z
vol.axis_min =  -10.0
vol.axis_max =  10.0
vol.bounding_polygon = 
 [[     0.5024     0.17949           0]
 [    0.49038     0.19551           0]
 [    0.49038     0.19872           0]
 [    0.48558     0.20513           0]
 [    0.48317     0.20513           0]
 [    0.48077     0.20833           0]
 [    0.48077     0.21474           0]
 [    0.47837     0.21795           0]
 [    0.47837     0.22115           0]
 [    0.47115     0.23077           0]
 [    0.47115     0.23718           0]
 [    0.46635     0.24359           0]
 [    0.46394     0.24359           0]
 [    0.46154     0.24679           0]
 [    0.46154     0.25321           0]
 [    0.45433     0.26282           0]
 [    0.45433     0.26603           0]
 [    0.45192     0.26923           0]
 [    0.45192     0.27244           0]
 [    0.44231     0.28526           0]
 [    0.44231     0.28